        "GlobalIndex": 1,
        "Name": "Рыцарь",
        "GlobalIndex": 2,
        "Name": "Архимаг",
        "GlobalIndex": 3,
        "Name": "Следопыт",
        "GlobalIndex": 4,
        "Name": "Ополченец",
        "GlobalIndex": 5,
        "Name": "Стражник",
        "GlobalIndex": 6,
        "Name": "Алебардист",
        "GlobalIndex": 7,
        "Name": "Гвардеец",
        "GlobalIndex": 8,
        "Name": "Пехотинец",
        "GlobalIndex": 9,
        "Name": "Оруженосец",
        "GlobalIndex": 10,
        "Name": "Воин-пилигрим",
        "GlobalIndex": 11,
        "Name": "Паладин",
        "GlobalIndex": 12,
        "Name": "Мечник",
        "GlobalIndex": 13,
        "Name": "Мастер меча",
        "GlobalIndex": 14,
        "Name": "Кирасир",
        "GlobalIndex": 15,
        "Name": "Рыцарь",
        "GlobalIndex": 16,
        "Name": "Дубинщик",
        "GlobalIndex": 17,
        "Name": "Воин с булавой",
        "GlobalIndex": 18,
        "Name": "Молотоборец",
        "GlobalIndex": 19,
        "Name": "Охотник",
        "GlobalIndex": 20,
        "Name": "Стрелок",
        "GlobalIndex": 21,
        "Name": "Лучник",
        "GlobalIndex": 22,
        "Name": "Егерь",
        "GlobalIndex": 23,
        "Name": "Арбалетчик",
        "GlobalIndex": 24,
        "Name": "Бомбардир",
        "GlobalIndex": 25,
        "Name": "Пушкарь",
        "GlobalIndex": 26,
        "Name": "Послушница",
        "GlobalIndex": 27,
        "Name": "Монашка",
        "GlobalIndex": 28,
        "Name": "Волшебница",
        "GlobalIndex": 29,
        "Name": "Святая",
        "GlobalIndex": 30,
        "Name": "Паломник",
        "GlobalIndex": 31,
        "Name": "Монах",
        "GlobalIndex": 32,
        "Name": "Священник",
        "GlobalIndex": 33,
        "Name": "Епископ",
        "GlobalIndex": 34,
        "Name": "Боевой монах",
    },
        "GlobalIndex": 35,
        "Name": "Церковный страж",
    },
        "GlobalIndex": 36,
        "Name": "Инквизитор",
        "GlobalIndex": 37,
        "Name": "Знахарь",
        "GlobalIndex": 38,
        "Name": "Волшебник",
        "GlobalIndex": 39,
        "Name": "Архимаг",
        "GlobalIndex": 40,
        "Name": "Кавалерист",
        "GlobalIndex": 41,
        "Name": "Конный Сержант",
        "GlobalIndex": 42,
        "Name": "Конный Рыцарь",
        "GlobalIndex": 43,
        "Name": "Мертвяк",
        "GlobalIndex": 44,
        "Name": "Мертвый воин",
        "GlobalIndex": 45,
        "Name": "Мертвый вождь",
        "GlobalIndex": 46,
        "Name": "Рыцарь смерти",
        "GlobalIndex": 47,
        "Name": "Упырь",
        "GlobalIndex": 48,
        "Name": "Вампир",
        "GlobalIndex": 49,
        "Name": "Носферату",
        "GlobalIndex": 50,
        "Name": "Вампирша",
        "GlobalIndex": 51,
        "Name": "Тень",
        "GlobalIndex": 52,
        "Name": "Дух",
        "GlobalIndex": 53,
        "Name": "Призрак",
        "GlobalIndex": 54,
        "Name": "Еретик",
        "GlobalIndex": 55,
        "Name": "Некролит",
        "GlobalIndex": 56,
        "Name": "Лич",
        "GlobalIndex": 57,
        "Name": "Ересиарх",
        "GlobalIndex": 58,
        "Name": "Дьяволист",
        "GlobalIndex": 59,
        "Name": "Нищий",
        "GlobalIndex": 60,
        "Name": "Крестьянин",
        "GlobalIndex": 61,
        "Name": "Староста",
        "GlobalIndex": 62,
        "Name": "Бандит",
        "GlobalIndex": 63,
        "Name": "Атаманша",
        "GlobalIndex": 64,
        "Name": "Убийца",
        "GlobalIndex": 65,
        "Name": "Грабитель",
        "GlobalIndex": 66,
        "Name": "Разбойник",
        "GlobalIndex": 67,
        "Name": "Разбойница",
        "GlobalIndex": 68,
        "Name": "Мародер",
        "GlobalIndex": 69,
        "Name": "Лжерыцарь",
        "GlobalIndex": 70,
        "Name": "Лорд изменник",
        "GlobalIndex": 71,
        "Name": "Святой брат",
        "GlobalIndex": 72,
        "Name": "Король",
        "GlobalIndex": 73,
        "Name": "Принцесса",
        "GlobalIndex": 74,
        "Name": "Идальго",
        "GlobalIndex": 75,
        "Name": "Купец",
        "GlobalIndex": 76,
        "Name": "Аббат",
        "GlobalIndex": 77,
        "Name": "Проклятый рыцарь",
        "GlobalIndex": 78,
        "Name": "Горожанка",
        "GlobalIndex": 91,
        "Name": "Дворянская дочь",
        "GlobalIndex": 80,
        "Name": "Лесной бандит",
        "GlobalIndex": 81,
        "Name": "Начальник стражи",
        "GlobalIndex": 82,
        "Name": "Викинг",
        "GlobalIndex": 83,
        "Name": "Колдунья",
        "GlobalIndex": 84,
        "Name": "Ведьма",
        "GlobalIndex": 85,
        "Name": "Культист",
        "GlobalIndex": 86,
        "Name": "Снайпер",
        "GlobalIndex": 87,
        "Name": "Асасин",
        "GlobalIndex": 88,
        "Name": "Злодей",
        "GlobalIndex": 89,
        "Name": "Атаман",
        "GlobalIndex": 92,
        "Name": "Яростный дух",
        "GlobalIndex": 93,
        "Name": "Чародейка",
        "GlobalIndex": 94,
        "Name": "Лучница",
        "GlobalIndex": 95,
        "Name": "Браконьер",
        "GlobalIndex": 96,
        "Name": "Вурдалак",
        "GlobalIndex": 97,
        "Name": "Некромант",
        "GlobalIndex": 98,
        "Name": "Нищенка",
        "GlobalIndex": 99,
        "Name": "Архилич",
        "GlobalIndex": 101,
        "Name": "Посланник Смерти",
        "GlobalIndex": 102,
        "Name": "Чумной доктор",
};